# Generated by Django 2.1.4 on 2019-03-11 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campreview', '0002_auto_20190311_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campsite',
            old_name='siteID',
            new_name='CampgroundID',
        ),
        migrations.RenameField(
            model_name='campsite',
            old_name='loop',
            new_name='campsiteID',
        ),
    ]
